repos:

  - repo: local
    hooks:
      - id: update-pre-commit
        # Keep pre-commits up to date:
        # Will BREAK commit when versions did change, so commit has to be re-initiated.
        name: update all hooks to latest
        language: system
        entry: pre-commit
        args:
          - autoupdate
        always_run: true
        pass_filenames: false
        fail_fast: true

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        # args: ["--severity=warning"]  # Optionally only show errors and warnings


  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: []
        # - "--line-length=100"
        # - "--check"
        # - "--diff"

  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: v3.15.0
  #   hooks:
  #     - id: reorder-python-imports

    # Avoid blanket NOQA use (should always have code attached)
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: run py.test and check coverage
  #       language: system
  #       entry: poetry run coverage run -m pytest
  #       types: [python]
  #       pass_filenames: false

  #     - id: pytest-cov
  #       name: run py.test and check coverage
  #       language: system
  #       entry: poetry run coverage report -m
  #       types: [python]
  #       pass_filenames: false
